### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by redtide** [agateau/colorpick#1]
In the desktop file there is a `fill-color` icon reference but it is not included in the repository, nor part of freedesktop icons spec, it could be possible to add it in the repository as resource to install via CMake?
Meanwhile I did an [AUR package](https://aur.archlinux.org/packages/colorpick-git/) for convenience for Archlinux users.

**Comment by agateau** [comment]
Thanks for the package! I am putting together a dedicated app icon, should be nicer than using a theme icon. Note that this adds extra-cmake-module has a build dependency.

**Comment by redtide** [comment]
Why extra module? Shouldn't an [install](https://cmake.org/cmake/help/latest/command/install.html) command be enough?
like
```cmake
install(FILES colorpick.png DESTINATION
    ${CMAKE_INSTALL_DATADIR}/icons/hicolor/48x48/apps)
```

**Comment by agateau** [comment]
The code is not yet in master because I am not super happy with the icon for now, so I am going to keep this open for now. But it's good to know it works on your side :+1:.

**Comment by redtide** [comment]
Yes it's OK, just proposing an alternative in case you were still not happy with it as you said.
It's basically like the current but with a color wheel instead white/violet background and a colored drop in the center.
