### ISSUE TITLE
Copy color as r,g,b

### ISSUE THREAD

**Issue by ghost** [agateau/colorpick#2]
I use colorpick **a lot** and would find it useful if  it could copy current color as "r,g,b" (e.g. 127,1,255) for use in Plasma 'color' files.

**Comment by agateau** [comment]
Great to hear you like it :)

This new format is a good idea. If you are familiar with C++, you can add it here: https://github.com/agateau/colorpick/blob/master/src/coloreditor.cpp#L184. Otherwise I will have a look when I have time.

**Comment by phobi4n** [comment]
Done. Thanks for that.

**Comment by agateau** [comment]
Actually, it would be nice to include this format to Colorpick itself :). Do you mind filing a pull request with your changes?

**Comment by phobi4n** [comment]
Github is complaining about Personal Access Tokens and the like so not gonna waste time with it. (Moved most of my stuff to opencode.net)

Fixed a compiler warning as well. The changes:
```
window.cpp line 22: change Window).dark(110  to .darker
coloreditor.cpp add line: addColorAction(tr("r,g,b Text"), QString("%1,%2,%3").arg(r).arg(g).arg(b));
```
