### ISSUE TITLE
Enable discussions

### ISSUE THREAD

**Issue by redtide** [agateau/colorpick#6]
I have some proposals and I see some stuff can be discussed instead opening issues:
- I need your POV on a single CMakeFile I did (I dislike mostly fragmented CMake scripts around instead 1 in a single place (except when is about modules). I added support also for Qt6
- I want to discuss about the possibility to limit dependencies, kwidgetsaddons might stay, though I did a "colorbutton" out of a clickable label, but kguiaddons seems about used only for a single, simple  [contrastRatio() function](https://www.w3.org/TR/WCAG/#dfn-contrast-ratio)
- I would like to change the directories structure and add an `appdata.xml` file:
```c
|_ src/ // stay as is
|_ resources/
  |_ freedesktop/
  | |_ colorpick.desktop
  | |_ colorpick.appdata.xml
  |_ icons/ // as is from /src
  |_ screenshots/ // as is or just put contrast.jpg as screenshot.jpg without this dir
  |_ app.qrc
```
EDIT: I made a mess with some pull requests because I'm not sure how make sequential changes in different PRs, I never did so many changes in a someone else project without having git access, will need your help/suggestions to how make it properly.

**Comment by agateau** [comment]
I don't have any prior experience with discussions, and I am not the most responsive person in the world, but let's give it a try :sweat_smile:. Just enabled them: https://github.com/agateau/colorpick/discussions

**Comment by redtide** [comment]
I don't think I have any particular experience more than you neither, maybe some IRC, but having a way to talk instead open non-issues is fine. If something goes really wrong like some spam, trolls or flames tsunami I guess you can just disable it :P
Other people here have little time so it happens to not have an answer, I think people understand it (also based on the repo activity).
